version: "3.7"

services:
  jobapp:
    container_name: app
    build: ./JobsApp/.
    ports:
      - 5000:80
    depends_on:
      - database
  
  database:
    container_name: jobappdb
    image: postgres:9.6.15-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true