version: "2.4"

services:
  jobapp:
    container_name: app
    build: ./JobsApp/.
    ports:
      - 5000:80
    depends_on:
      database:
        condition: service_healthy
  
  database:
    container_name: jobappdb
    image: postgres:9.6.15-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
    external: true