{
 "title": "Nginx Responses Overview",
 "description": "Shows stats built from the Prometheus Nginx mtail log exporter rebuy-de/nginx-exporter or ndiazg/nginx-prometheus-exporter.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(nginx_up, namespace)"
   },
   {
    "name": "vhost",
    "query": "label_values(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\"}, vhost)"
   },
   {
    "name": "code",
    "label": "response_code",
    "query": "label_values(nginx_request_duration_milliseconds_count, code)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_requests_total{namespace=~\"$namespace\",vhost=~\"$vhost\",code=~\"$code\",host!=\"127.0.0.1\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_requests_total{namespace=~\"$namespace\",vhost=~\"$vhost\",code=~\"$code\",host!=\"127.0.0.1\"}[5m])) by (vhost,code)",
     "legendFormat": "{{code}} {{vhost}}"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(nginx_request_duration_milliseconds_bucket{namespace=~\"$namespace\",vhost=\"$vhost\",host!=\"127.0.0.1\",le=\"100\"}[1m]))+sum(rate(nginx_request_duration_milliseconds_bucket{namespace=~\"$namespace\",vhost=\"$vhost\",host!=\"127.0.0.1\",le=\"200\"}[1m]))) / 2 / sum(rate(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\",vhost=\"$vhost\",host!=\"127.0.0.1\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_milliseconds_sum{namespace=~\"$namespace\",vhost=~\"$vhost\",host!=\"127.0.0.1\"}[1m])) / sum(rate(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\",vhost=~\"$vhost\",host!=\"127.0.0.1\"}[1m]))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "Response time by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_milliseconds_sum{vhost=\"$vhost\",host!=\"127.0.0.1\"}[1m])) by (vhost) / sum(rate(nginx_request_duration_milliseconds_count{vhost=\"$vhost\",host!=\"127.0.0.1\"}[1m])) by (vhost)",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(nginx_request_duration_milliseconds_count{host!=\"127.0.0.1\",vhost=\"$vhost\"}) by (vhost))"
    }
   ]
  }
 ]
}