{
 "title": "Nginx General Overview",
 "description": "Shows stats built from the Prometheus Nginx mtail log exporter rebuy-de/nginx-exporter or ndiazg/nginx-prometheus-exporter.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(nginx_up, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(nginx_up{namespace=~\"$namespace\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_milliseconds_sum{namespace=~\"$namespace\",app=~\"$app\"}[5m])) by (namespace, app) / sum(rate(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\",app=~\"$app\"}[5m])) by (namespace, app)",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\",app=~\"$app\"}[1m])) by (namespace, app)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_milliseconds_count{namespace=~\"$namespace\",app=~\"$app\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "graph",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_response_size_bytes_sum{namespace=~\"$namespace\",app=~\"$app\"}[5m])) by (namespace, app)",
     "legendFormat": "traffic bytes"
    }
   ]
  }
 ]
}