global:

  scrape_interval:     15s
  evaluation_interval: 15s

# rule_files:
#  - 'alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  
  - job_name: "node"
    scrape_interval: "5s"
    static_configs:
      - targets: ['nodeexporter:9100']

  
  - job_name: "container"
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: "postgres_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ['postgresexporter:9187']

#alerting:
#  alertmanagers:
#    - static_configs:
#      - targets: 
#        - alertmanager:9093